### ISSUE TITLE
Waypoints appear late in intersection

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1477] opened 2022-06-24 16:08 UTC
## **BUG REPORT**
**High Level Description**
Vehicles driving through an intersection will cause alternate lane waypoints to show up when already almost completely through the intersection. 

**SMARTS version**
0.6.1.rc0

**Previous associated issues**
#1469

**Steps to reproduce the bug**
Check out https://github.com/huawei-noah/SMARTS/commit/e6dfc2cfed882631e9423787603eff0b12b4fc81

```bash
git checkout e6dfc2cfed882631e9423787603eff0b12b4fc81
scl envision start &
# Open web-browser to localhost:8081
python examples/target_pose_example.py
```

**Resulting and expected behaviour**
Waypoints show unusual behaviour going through intersection.

@Adaickalavan @sah-huawei

**Comment by sah-huawei** [comment] 2022-07-12 06:44
So far, I have discovered 2 bugs that contributed to the problem, both of which are already fixed on the `develop` branch:

1. The `length` property reported for lanes was incorrect.  In this case, the length of lane "E35-3_2" is reported as 100.0 when it is actually 111.5.    This means that the code that "backtracks" by 20 meters in order to start the waypoint paths behind the vehicle's current location gets messed up as soon as the vehicle enters the junction and it has to backtrack into the previous lane (because it tries to subtract from `lane.length`).
2.  The `incoming_lanes` property (used for the aforementioned backtracking) did not correctly include "junction-internal" lanes, meaning that upon exiting the junction, the starting point for the waypoints would be incorrect.

In addition to these 2 bugs, I discovered that our code for reporting parallel roads will report roads (edges) for _all_ internal lanes within a junction as being parallel.   This behaviour goes back a long way, to way before the `RoadMap` refactor, which didn't change it.  This means that upon entering a junction there will be waypoints from all of the crossing lanes that show up in the `RoadWaypoints` sensor too.  

I think this is the intended behaviour for the sensor, but I point it out here because I _don't_ think this is the intended behaviour for the `parallel_lanes` API.   Other implementations of `RoadMap` (i.e., OpenDRIVE and/or Waymo) may not behave this way.  For these map formats, we may not get the same crossing waypoints in intersections.  And if we ever want to update/fix `SumoRoadMap` to make it consistent with the others, we will need to address this too.

**Comment by sah-huawei** [comment] 2022-07-12 07:02
I tested this on `develop` and it seems fine to me.  @Gamenot, please check there and let me know if we can resolve this.

(Also, fwiw, I just added a comment to `sumo_road_network.py` in the `parallel_roads` method about the fact that it returns all roads within junctions.)

**Closed** 2023-04-21 16:07 UTC
Labels: bug
