### ISSUE TITLE
Envision multi-instance display

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#784] opened 2021-04-21 14:06 UTC
## **BUG REPORT**
Unable to view multi-instance display when "All Simulations" is selected in Envision while running multiple SMARTS instances.

**SMARTS version**
0.4.15

**Previous associated issues**
None

**Steps to reproduce the bug**
1) Start envision in a terminal
    ```
    $ scl envision start -s ./scenarios -p 8081
    ```
2) Start SMARTS simulation in another terminal
    ```
    $ python3.7 ./examples/multi_agent.py ./scenarios/intersections/6lane/
    ```

**Resulting and expected behaviour**
Expected: Able too see multi-instance display in Envision when "All Simulations" options is selected.

![image](https://user-images.githubusercontent.com/8764693/122244324-cc1e0a80-ce92-11eb-9692-440c801cad5c.png)

**Error logs and screenshots**
None
 
**System information**- Operating system & Environment [Please note if using Docker]: Ubuntu 16.04
- Number of system cores available: 16
- Python version [Please note if using Jupyter]: Python3.7
- Python packages [e.g. from `pip freeze`]
- SUMO version: 1.8.0
- Date when bug occurred: 19 April 2021

**Impact [If known]**
Unable to view multi-instance display in Envision.

**Comment by RutvikGupta** [comment] 2021-06-16 16:00
Something related to this was addressed in PR #363. But that was fixed before this issue was noticed.

**Comment by RutvikGupta** [comment] 2021-06-21 15:38
After tracking down, the git commit history, it seems like the multi-instance display stopped working after SMARTS version 0.4.14 release. (https://github.com/huawei-noah/SMARTS/commit/c8473049b4b52ad3eb29f7c7eb93753c2d70df55)

**Comment by RutvikGupta** [comment] 2021-06-21 16:27
After some more investigation, its safe to say that the issue is arising from changes done to the `.js` files in this release. Changes to the `client.py` or other files dont seem to be the issue.

**Comment by RutvikGupta** [comment] 2021-06-21 18:54
PR #575 and #547 were made to the JavaScript files after SMARTS version 0.4.13 release and before SMARTS version 0.4.14 release which caused the multi-instance display to stop working.

**Comment by RutvikGupta** [comment] 2021-06-21 20:25
Actually PR #580 is the cause of this issue.

**Comment by RutvikGupta** [comment] 2021-06-21 22:10
Also for PR #545, the following code snippet in `app.js` tries to reconnect to a single simulation every time, you switch to "All Simulations".
![image](https://user-images.githubusercontent.com/47334253/122834057-ed7c5d80-d2bb-11eb-9b1e-bd9d7ddd4d41.png)
Removing it fixes that issue for that PR.

**Comment by RutvikGupta** [comment] 2021-06-21 22:44
Ok, so I found the bug. Will open a PR soon.

**Closed** 2021-06-24 15:05 UTC
Labels: bug
