### ISSUE TITLE
Scenario Metadata Files

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1645] opened 2022-09-26 15:37 UTC
Regeneration of scenario resources should only occur if a resource has changed.
- Full optimization requires a dependency tree
- A resource should be regenerated when:
  - The resource file has been updated
  - The resource depends on another resource that has been updated
  - The resource has changed its dependencies
  - The version of SMARTS has changed since the resource was built
- This should result in a general improvement in scenario build time

**Comment by saulfield** [comment] 2022-11-17 20:50
Duplicate of #1595.

**Closed by saulfield** 2022-11-17 20:50 UTC
Labels: enhancement, performance improvement, long term
