### ISSUE TITLE
[Help Request] traci

### ISSUE THREAD

**Issue by knightcalvert** [huawei-noah/SMARTS#2139] opened 2024-01-19 02:42 UTC
### High Level Description

I have noticed i have the same problem with #2127,  so i update the latest smarts version. but the problems still exist.
problem 1 :
```
Could not connect to TraCI server at localhost:59573 [Errno 111] Connection refused
 Retrying in 0.05 seconds
Could not connect to TraCI server at localhost:59573 [Errno 111] Connection refused
 Retrying in 0.05 seconds
Could not connect to TraCI server at localhost:59573 [Errno 111] Connection refused
 Retrying in 0.05 seconds
```
in the beginning, the traci will tried to connect to different ports. however, after running 10 hours, the traci only tried to connect to the same port with constant failure, so my code stucked, i have to rerun my code.

problem 2 :
this problem is like the #2127, because of 
```
  File "./smart_master/SMARTS/smarts/core/sumo_traffic_simulation.py", line 239, in _initialize_traci_conn
    self._traci_conn.setOrder(0)
TypeError: 'NoneType' object is not callable
```
so my smarts can't reset successfully, i update the code, but this problem still exist occasionally.

and can i **ture off this traci warning?**  90% of my console output is traci warning, I can't find the info i really need. thank you very much

### Version

the latest v

### Operating System

ubuntu

**Comment by Gamenot** [comment] 2024-01-19 06:47
Hello @knightcalvert, we are currently using [this method](https://stackoverflow.com/questions/1365265/on-localhost-how-do-i-pick-a-free-port-number/45690594#45690594) to acquire port numbers for SUMO.


I did a bit of digging into SUMO [port creation](https://github.com/eclipse-sumo/sumo/blob/56aceb87d847397941936c28934f9097e0c03f98/src/foreign/tcpip/socket.cpp#L269-L335) and [shutdown](https://github.com/eclipse-sumo/sumo/blob/56aceb87d847397941936c28934f9097e0c03f98/src/foreign/tcpip/socket.cpp#L148-L173). I think perhaps this line killing SUMO is preventing the destructor being called and cleanup of SUMO's used port. 
https://github.com/huawei-noah/SMARTS/blob/e2144e1e99cf2326e36c32388d3e0687dbfd0d4d/smarts/core/utils/sumo.py#L226 
I'll try tomorrow to see if I can apply a cleaner shutdown without blocking on sumo closing.

I will also squash the messages. They are related one of sumo's methods that uses print for warnings...:

https://github.com/eclipse-sumo/sumo/blob/56aceb87d847397941936c28934f9097e0c03f98/tools/traci/main.py#L87-L106

**Comment by Gamenot** [comment] 2024-01-19 19:28
An update. `kill()` was intended to prevent zombie SUMO processes, without it some `sumo` zombie processes can be left behind. I am trying to find a solution that closes `sumo` processes gracefully but does not leave behind zombie processes.

**Comment by Gamenot** [comment] 2024-01-20 08:11
#2140 is intended to fix the issue. From current stress testing, `kill()` does not leave over zombie processes or lost ports. Processes exiting without closing the `sumo` process will cause zombie processes, mainly in the case of an exception or closing a process without calling `SMARTS.destroy()` inside. I have going to run a second set of stress tests to see if reusing a single process causes a problem.

@knightcalvert One thing to note, even after this, if you are using SMARTS directly make sure that each SMARTS instance calls `destroy()` at the end of its use to guarantee cleanup of resources. If using the the `gym` style environment `close()` is necessary.

**Comment by knightcalvert** [comment] 2024-01-22 09:00
after updating the code, it helpful, the useless output is gone. 
but maybe because of my parallel run? i still got: 
```
[] TraCI could not connect in time to 'localhost:52151' [Could not connect in 101 tries]
[] TraCI could not connect in time to 'localhost:52151' [Could not connect in 101 tries]
[] TraCI could not connect in time to 'localhost:52151' [Could not connect in 101 tries]
```
and my code have using close()
```
    def close(self):
        self.base_env.close()
```
i‘m not familiar with the traci or ports, and just curious that if one port could not connect in many tries, it seems useless to continue connecting this port, can i tried to connect another one?

**Comment by Gamenot** [comment] 2024-01-22 17:52
> after updating the code, it helpful, the useless output is gone.
> but maybe because of my parallel run? i still got:
> 
> ```
> [] TraCI could not connect in time to 'localhost:52151' [Could not connect in 101 tries]
> [] TraCI could not connect in time to 'localhost:52151' [Could not connect in 101 tries]
> [] TraCI could not connect in time to 'localhost:52151' [Could not connect in 101 tries]
> ```

I think I understand the issue better now. It does not seem to have to do with number of ports but with the SUMO server and SMARTS somehow not paring.

My only thought is that somehow this is happening:

![sumo_problem](https://github.com/huawei-noah/SMARTS/assets/8764693/1f39b3b1-add8-40ce-903a-77470814d809)

Once a connection is established, `SMARTS` does not check to see if its instance of the TraCI server (`sumo`) is still alive. So, I think this might be the result of an extremely low probability race condition where a smarts instance manages to connect to a different TraCI server by bad luck, then locking out the actual owner of the TraCI server.

We get ports by getting a random free port recommended by the OS (out of 64512 standard ports), so the chance of ports colliding is very low but possible.

> and my code have using close()
> 
> ```
>     def close(self):
>         self.base_env.close()
> ```
>
> i‘m not familiar with the traci or ports, and just curious that if one port could not connect in many tries, it seems useless to continue connecting this port, can i tried to connect another one?

It was assumed that it would connect or retry with a different port. I will put in a patch that will reattempt with a different port while I think of a way to gracefully handle the root cause.

> problem 2 :

Does this still happen?

**Comment by Gamenot** [comment] 2024-01-22 19:10
> i‘m not familiar with the traci or ports, and just curious that if one port could not connect in many tries, it seems useless to continue connecting this port, can i tried to connect another one?

I have attempted a patch 0930736 for that now in #2140. It retries with a different port and saves the TraCI server on a failed connection to avoid interrupting a different instance.

**Comment by knightcalvert** [comment] 2024-01-23 02:40
my last run is stucked in 401027 episodes, as far as i know, the problem 2 is not happened again. I roughly understand what you say, it seems like if i reduce the number of parallel runs, the possibility of port occupation will reduce too? 
really thank you for your constant attention.

**Comment by Gamenot** [comment] 2024-01-23 05:13
> my last run is stucked in 401027 episodes, as far as i know, the problem 2 is not happened again. I roughly understand what you say, it seems like if i reduce the number of parallel runs, the possibility of port occupation will reduce too? really thank you for your constant attention.

Honestly, it would reduce the chances but not completely prevent it.

I am pursuing a different solution that uses a centralised server. As of 94da02f it looks like this:


```bash
# console 1 (or in background)
$ python -m smarts.core.utils.sumo_server
```

```bash
# console 2
# Set environment variable
$ export SMARTS_SUMO_SERVE_MODE=remote
## do run
$ python experiment.py
```

**Comment by Gamenot** [comment] 2024-01-25 20:06
The newest change resulted in no disconnects and no port collisions against 60k instances and 32 parallel experiments.

**Closed** 2024-02-05 00:41 UTC
Labels: help wanted

**Comment by Apoorvgarg-creator** [comment] 2024-09-07 22:33
Hi @Gamenot I am still facing the issue for TraCI server.

I ran the cmd `python -m smarts.core.utils.centralized_traci_server` on 1 console.

Then I ran in 2nd console
`export SMARTS_SUMO_TRACI_SERVE_MODE=central`
and also ran the example code of SMARTs.
I am able to see red cars only.
