### ISSUE TITLE
abnormal dist_reward

### ISSUE THREAD

**Issue by qianyi-sun** [huawei-noah/SMARTS#1656] opened 2022-10-04 14:04 UTC
Using waymo dataset to train the track2 baseline (`track2/train/train.py`), when the ego drives at constant slow speed, the distance reward cyclically repeats in range of 0-0.6, see the screenshot below. By randomly sampled 10 scenarios, there are 3 of them have this issue, which are 3714ba3e1d32f18b，12944efe8c17aad8，cf52b5f204baee0b. Thanks!

![2fb81c1500eb60442e86e136c303ce7](https://user-images.githubusercontent.com/59240680/193839505-8fdcbfda-f9fa-4544-befc-ea0f1d9250e1.png)

**Comment by Gamenot** [comment] 2022-10-05 01:08
Thank you for bringing up this issue. This appears to be a bug in the trip meter sensor. For reference the issue was the following:

![image](https://user-images.githubusercontent.com/8764693/193957663-39350181-491b-4912-ae58-3f141643cd56.png)


Dot product was cast between recorded trip waypoints. The issue is that the previous waypoint from the 0.5 meter travel history interval was being used for the vehicle displacement component of the dot product instead of the previous vehicle position. This resulted in a distance value based on the previous waypoint accumulating until the next 0.5 meter increment.

**Comment by Gamenot** [comment] 2022-10-06 18:50
The fix has been merged into the competition.

**Closed** 2022-10-12 13:37 UTC
Labels: help wanted
