### ISSUE TITLE
Abnormal collision with imitation learning

### ISSUE THREAD

**Issue by zbzhu99** [huawei-noah/SMARTS#969] opened 2021-06-28 03:14 UTC
## **BUG REPORT**
**High Level Description**
The history replacement agent will terminate with collision frequently

**Details**
I train the imitation learning agent on NGSIM map using SMARTS of 4c829edd7535eaf0e79b57d384fdaf8711226978. When I update SMARTS to the newest develop branch and test the model, the trained agent seems to have much more collisions than expected. 

From my test, the abnormal collision is likely related to 8bdbba22864b2f13e80dbd04bfb17d98f76724d5.

**Comment by zbzhu99** [comment] 2021-06-30 08:11
This is the map file I used:

[map.net.xml.zip](https://github.com/huawei-noah/SMARTS/files/6739167/map.net.xml.zip)

**Comment by sah-huawei** [comment] 2021-06-30 19:31
@zbzhu99 Thanks.  The good news is that you're using the most current one, which is at 1:1 scale.  Assuming both (a) the history dataset (`.shf`) file you are using was re-generated (`scl build --clean...`) with the `.yaml` file in your zip folder, and (b) the model you are testing now was trained using this same dataset (`.shf`)  and map (`.net.xml`) at 1:1 scale, then everything should work.  But if either (a) or (b) are incorrect assumptions, then this could explain the behavior you are seeing.

Please let me know about (a) and (b) and then I will try to debug accordingly.  Thanks for your patience!

**Comment by zbzhu99** [comment] 2021-07-02 05:59
When I rebuild the scenario, the map now looks weird:

**Comment by sah-huawei** [comment] 2021-07-02 23:23
How odd!  This appears to be a problem with the `map.glb` created for and used by Envision.  I'm able to reproduce it here.  The `map.net.xml` file seems fine (both in `netedit` and in `sumogui`), so I suspect this is just a visualization problem (i.e., the data should still be ok), but I will dig into it further (espcially to see if it the problem might relate to collisions too) and report back.

**Comment by sah-huawei** [comment] 2021-07-02 23:54
@RutvikGupta This (the `map.glb` problem,not the collision issue) appears to be related to PR #901.  (I reverted to just before that and the `map.glb` appears fine in Envision.)  Could you please help us to fix that part?  Meanwhile, I'll continue to investigate the collision issue.  Thanks!

**Comment by RutvikGupta** [comment] 2021-07-03 00:08
Sure, I will have a look.

**Comment by RutvikGupta** [comment] 2021-07-05 13:56
Which scenario was used to run the test? I don't see the visualization issue in existing set of scenarios.

**Comment by RutvikGupta** [comment] 2021-07-05 17:03
So, I investigated the visualization issue and found that NGSIM map consist of many internal lane gaps because of the way it was created by SUMI and snapping them causes the visualization to distort since all edges are marked as normal edges when many of them are internal edges. So I modified the map.net.xml file by adding a `type = ignore_snapping` flag to the edge queries in `map.net.xml` so that the external snapping won't take place for them. 

This is a better workaround because it modifies the `map.net.xml` to a minimal extent without changing the map and also I don't have to modify the snapping functions which will cause the existing set of scenario maps to break the fix in PR #901. 

@zbzhu99 Please use this scenario map for testing and review the PR #992 to check out the changes.

**Comment by zbzhu99** [comment] 2021-07-06 01:58
The map visualization issue has been resolved with the fixed map and `ngsim-map-holes` branch, but the collision issue still exists.

**Closed** 2023-04-21 17:37 UTC
Labels: bug, imitation
