### ISSUE TITLE
Docker instructions do not work

### ISSUE THREAD

**Issue by behrisch** [huawei-noah/SMARTS#472] opened 2021-01-23 17:49 UTC
The docker instructions in https://github.com/huawei-noah/SMARTS#using-docker have several issues:
1. `docker run --rm -it -v $(PWD):/src -p 8081:8081 huaweinoah/smarts:v0.4.3-pre` gives `PWD: command not found`
2. using `docker run --rm -it -v $PWD:/src -p 8081:8081 huaweinoah/smarts:v0.4.3-pre` (no brackets around PWD) and `scl envision start -s ./scenarios -p 8081 &` gives `bash: scl: command not found`
3. using `docker run --rm -it -v $PWD:/src -p 8081:8081 huaweinoah/smarts:v0.4.9` and `scl envision start -s ./scenarios -p 8081 &` gives
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (grpcio 1.32.0 (/usr/local/lib/python3.7/dist-packages), Requirement.parse('grpcio==1.30.0'), {'smarts'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/scl", line 33, in <module>
    sys.exit(load_entry_point('smarts', 'console_scripts', 'scl')())
...
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'grpcio==1.30.0' distribution was not found and is required by smarts
```

**Comment by Gamenot** [comment] 2021-01-25 02:28
Hello @behrisch, thank you for reaching out and sorry for any problems you are having here. 

We have updated the docker images. There should be a v0.4.12 out now.

Thank you for warning us about the docker instructions, we keep finding that our documentation quickly goes out of date. It will be updated with #474.

In terms of context for the issue:

Our use case for SUMO is for reinforcement learning so there are a number of unusual uses we have for SUMO. The first is that there is non-trivial vehicle motion. The second is that we like to take over existing vehicles in the traffic simulation after the simulation has warmed up, using more complex models to control vehicles that enter specific areas and releasing them when they exit.

We originally ran into the issue around sumo 1.5 but it has been existing since well before then from my own knowledge.

This is an another example crash from sumo 1.6.0+dfsg1-1 [origin: LP-PPA-sumo-stable]
[_usr_bin_sumo.1002.crash.log](https://github.com/huawei-noah/SMARTS/files/5863698/_usr_bin_sumo.1002.crash.log)

We have found that calling `_traci_conn.vehicle.moveToXY()` on a vehicle has been controlled by SUMO can cause the lane changer to lose track of some information and at some point SUMO will attempt to use a null pointer (especially on return of a vehicle to SUMO'S control.)

Our solution was to remove the vehicle and then re-add it back a step later. While this has worked for us in the past, the solution itself causes other problems mainly around handling the issue a vehicle disappearing for a step. Some changes attempting to address that issue resulted in a regression causing the bug to reassert itself.

I could suggest closing https://github.com/eclipse/sumo/issues/8125 until we get a better example to you. On our side we will attempt to create an example that quickly runs into the problem.

**Comment by Gamenot** [comment] 2021-01-25 02:43
@Adaickalavan We will talk about this tomorrow.

**Comment by behrisch** [comment] 2021-01-25 16:57
> I could suggest closing [eclipse/sumo#8125](https://github.com/eclipse/sumo/issues/8125) until we get a better example to you. On our side we will attempt to create an example that quickly runs into the problem and then raise the issue again.

Yes, I think this is a good idea. Please also try to use the latest SUMO if possible.

**Closed** 2021-02-01 20:54 UTC
Labels: Urgent, bug
