### ISSUE TITLE
## About ego-vehicle reset delay

### ISSUE THREAD

**Issue by YuechengLiu** [huawei-noah/SMARTS#1425] opened 2022-05-09 08:00 UTC
https://github.com/huawei-noah/SMARTS/issues/1407#issuecomment-1111605607
> Then the problem is the following even if we get the `traffic_history_provider` to move to a different time:
> ```python
>>> ## assuming first agent mission start time is 0
>>> start_time = 10
>>> traffic_history_provider = smarts.get_provider_by_type(TrafficHistoryProvider)
>>> traffic_history_provider.start_time = start_time
>>> smarts_obs = smarts.reset(scenario) # <-- issue occurs here and does not return immediately
>>> thp_time = start_time + smarts.elapsed_sim_time
>>> expected_time = start_time + smarts.fixed_timestep_sec
>>> assert thp_time <= expected time
>~AssertionError 10.5 <= 10.1```

The ego-vehicle-reset problem still exists after the update [https://github.com/huawei-noah/SMARTS/pull/1412](url).

Why can't smarts return the ego-vehicle immediately? What is happening during the time? 

I also observe that the delay times are different for different ego-vehicles (for about 0.2s ~ 1.xx s). Can we eliminate this delay time? The time delay is harmful since traffic-history-based vehicles are still running.

**Comment by Gamenot** [comment] 2022-05-09 20:10
This seems surprising to me. I would expect the maximum time difference to take over the first ego-vehicle to be a single simulation step (0.1s) by default.

One thing now is that you should no longer set the following line or it will desynchronize the simulation with the traffic history:

```python
traffic_history_provider.start_time = start_time # < remove this line if it exists
smarts.reset(scenario, start_time) # use this instead
```

After which the following should hold true as long as using `default_entry_tactic(..)`:

```python
missions = scenario.history_missions_for_window(10, 30, 10)
s = random.sample(missions, 3)
start_time = min(m.start_time for m in missions) 
logger.info(f"Simulation start time is: {start_time}") # > "Simulation start time is: 10.4
smarts_obs = smarts.reset(scenario, start_time=start_time)
assert smarts.elapsed_sim_time == start_time + smarts.fixed_timestep_sec
```

**Comment by Gamenot** [comment] 2022-05-09 20:12
On further reflection, I can think of one potential edge case of inaccurate vehicle capture if multiple agents are involved. I will look into it now.

**Comment by YuechengLiu** [comment] 2022-05-10 00:44
> This seems surprising to me. I would expect the maximum time difference to take over the first ego-vehicle to be a single simulation step (0.1s) by default.
> 
> One thing now is that you should no longer set the following line or it will desynchronize the simulation with the traffic history:
> 
> ```python
> traffic_history_provider.start_time = start_time # < remove this line if it exists
> smarts.reset(scenario, start_time) # use this instead
> ```
> 
> After which the following should hold true as long as using `default_entry_tactic(..)`:
> 
> ```python
> missions = scenario.history_missions_for_window(10, 30, 10)
> s = random.sample(missions, 3)
> start_time = min(m.start_time for m in missions) 
> logger.info(f"Simulation start time is: {start_time}") # > "Simulation start time is: 10.4
> smarts_obs = smarts.reset(scenario, start_time=start_time)
> assert smarts.elapsed_sim_time == start_time + smarts.fixed_timestep_sec
> ```

I know that, what I am using is exactly the new inferface, but the problem still exists.
In my experiments, only one ego-vehicle is specified in each scenario.

**Comment by YuechengLiu** [comment] 2022-05-10 00:49
Is the problem reproducible in your experiment？

**Comment by Gamenot** [comment] 2022-05-10 03:51
> Is the problem reproducible in your experiment？
I have reproduced the problem and linked it back to a case I did not know existed. I am slightly surprised traffic history even worked up to this point.

**Comment by Gamenot** [comment] 2022-05-10 04:03
I am putting up a fix now.

**Comment by Gamenot** [comment] 2022-05-10 04:09
It still looks like there is up to a +1 step variance. I will try to hunt that issue down tomorrow.

**Comment by YuechengLiu** [comment] 2022-05-10 04:28
ok, thanks for the work!

**Comment by Gamenot** [comment] 2022-05-10 04:51
The fix is merged into develop along with changes in #1417.

**Comment by Gamenot** [comment] 2022-05-10 14:07
@YuechengLiu This changeset merged with #1417 appeared to fix the significant delay issue for me: https://github.com/huawei-noah/SMARTS/pull/1417/commits/2c9c7a0f08c17dcc1cb30d28a23fb736c2ff294d

Could you confirm that it removes the variance that is greater than 2 steps?

**Comment by YuechengLiu** [comment] 2022-05-10 14:12
@Gamenot 
The [PR](https://github.com/huawei-noah/SMARTS/pull/1417) works. There are no time delay greater than 2 steps in my experiments now.

**Comment by Gamenot** [comment] 2022-05-10 20:41
I can confirm that there is a 1 step fixed delay. It appears like it may be a fundamental problem since the capture occurs after physics. I am working through the issue.

**Comment by Gamenot** [comment] 2022-05-10 20:59
@YuechengLiu There is a workaround at current which will replace the vehicle at the correct time:

smarts.reset(scenario, max(0, history_start_time-smarts.fixed_timestep_sec))

**Closed** 2022-05-30 18:00 UTC
