### ISSUE TITLE
[smarts-service] case run with error

### ISSUE THREAD

**Issue by charleschen6** [huawei-noah/SMARTS#168] opened 2020-11-17 06:20 UTC
Run case in scenarios/kyber/README.md
after stop first scenario, then start next scenario with below error and sumo view has no vehicle display

```shell
ERROR:tornado.application:Uncaught exception GET /reset (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/reset', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/chendong/.venv-py3.7.6/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "smarts/service/server.py", line 136, in get
    manager.reset()
  File "smarts/service/server.py", line 107, in reset
    self._smarts.reset(scenario)
  File "/home/chendong/codes/github/SMARTS/smarts/core/smarts.py", line 268, in reset
    self.teardown()
  File "/home/chendong/codes/github/SMARTS/smarts/core/smarts.py", line 378, in teardown
    self._bullet_client.resetSimulation()
pybullet.error: Not connected to physics server.
ERROR:tornado.access:500 GET /reset (127.0.0.1) 150.26ms
```

**Comment by liamchzh** [comment] 2020-11-18 04:46
The root cause is #179, close this one.

**Closed by liamchzh** 2020-11-18 04:46 UTC
