### ISSUE TITLE
Memory keeps growing

### ISSUE THREAD

**Issue by guanjiayi** [huawei-noah/SMARTS#794] opened 2021-04-25 12:00 UTC
**High Level Description**
[Memory keeps growing during model training]

**Desired SMARTS version**
[Docker 0.4.12]

**Operating System**
[ubuntu 18.04]

**Problems**
[1. Memory keeps growing during model training, until exceeds the maximum physical memory;
2.  The memory is also growing when running the _single_agent.py_ of the examples ]

**Comment by Gamenot** [comment] 2021-04-26 18:25
@guanjiayi Hello, I cannot reproduce a massive memory growth. How fast do you expect the memory to grow? 

Perhaps are you are using envision? If that is the case it will save a buffer of up to 500mb of simulation history per simulation by default. The impact of this buffer can be addressed by limiting the envision buffer with the `-c` option (i.e. `scl envision start -c 20`).

**Comment by guanjiayi** [comment] 2021-04-27 01:42
Thank you for you reply.  I do use Envision, but do not start the envision it will prompt an error. 
ERROR:Client:Connection to Envision terminated with: [Errno 99] Cannot assign requested address
When the model runs more than 1000 episode, the memory exceeds 16GB.

**Comment by guanjiayi** [comment] 2021-04-27 02:01
when i start the envision by "scl envision start -c 20 -s ./scenarios -p 8081 &", the memory is still grow fast.

**Comment by guanjiayi** [comment] 2021-04-27 02:21
Can I disable envision and eliminate the error?

**Comment by sah-huawei** [comment] 2021-04-27 02:57
@guanjiayi To disable envision, you can run with the `--headless` command line flag.

**Comment by guanjiayi** [comment] 2021-04-27 03:13
@Gamenot @sah-huawei I run my model by `python rlagentmodel/sacagent_d/sacagent_d_20210425.py --headless ./scenario/loop` the memory is still grow fast.

**Comment by Gamenot** [comment] 2021-04-28 04:03
OK, I will try to look at `single_agent.py` again to see if I can get a leak out of it. 

Are you using any particular scenario? Also, what observations do you have active from the `AgentInterface`?

**Comment by guanjiayi** [comment] 2021-04-28 12:01
Thank you very much!

**Comment by Gamenot** [comment] 2021-04-29 15:06
@guanjiayi I am sorry for the length of time it took to discover where the problem is coming from. I have done some tests and confirmed that the configurations from the AgentInterface are not causing leaks. However, I have confirmed that the `intersection/loop` scenario has a bad memory leak and that the `rl-agent:rl-agent-v0` agents also does not properly manage memory. I am trying to narrow down the specific source of the problem.

This problem also appears to exist on all versions of SMARTS.

**Closed** 2021-06-03 19:05 UTC
Labels: help wanted
